from .user import User
from .driver import Driver
from .vehicle import Vehicle
from .shipment import Shipment
from .shipment_event import ShipmentEvent
from .trip import Trip
from .gps_tracking import GPSTracking
from .maintenance import VehicleMaintenance
from .fuel_record import FuelRecord
from .notification import Notification
from .attendance import Attendance