"""sync shipment trip notification constraints

Revision ID: 005e98efab7b
Revises: 7248cad04b1e
Create Date: 2026-08-11 16:00:27.105806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '005e98efab7b'
down_revision: Union[str, Sequence[str], None] = '7248cad04b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('shipments', 'tracking_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('shipments', 'source',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('shipments', 'destination',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('shipments', 'customer_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('shipments', 'shipment_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('shipments', 'status',
               existing_type=postgresql.ENUM('Created', 'Assigned', 'In_Transit', 'Delayed', 'Delivered', 'Cancelled', name='shipmentstatus'),
               nullable=False)
    op.create_unique_constraint(None, 'shipments', ['tracking_number'])
    op.alter_column('trips', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('trips', 'driver_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('trips', 'shipment_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'shipment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('trips', 'driver_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('trips', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'shipments', type_='unique')
    op.alter_column('shipments', 'status',
               existing_type=postgresql.ENUM('Created', 'Assigned', 'In_Transit', 'Delayed', 'Delivered', 'Cancelled', name='shipmentstatus'),
               nullable=True)
    op.alter_column('shipments', 'shipment_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('shipments', 'customer_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('shipments', 'destination',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('shipments', 'source',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('shipments', 'tracking_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
