"""Add alert_sent to vehicle_maintenance

Revision ID: 00d6db80aadf
Revises: 76457837c2d0
Create Date: 2026-08-14 13:30:01.815468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d6db80aadf'
down_revision: Union[str, Sequence[str], None] = '76457837c2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_maintenance', sa.Column('alert_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_maintenance', 'alert_sent')
    # ### end Alembic commands ###
