"""add gps tracking fields

Revision ID: 0616a78a5b94
Revises: 005e98efab7b
Create Date: 2026-08-11 17:29:58.821729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0616a78a5b94'
down_revision: Union[str, Sequence[str], None] = '005e98efab7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps_tracking', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('gps_tracking', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('gps_tracking', sa.Column('speed', sa.Float(), nullable=False))
    op.add_column('gps_tracking', sa.Column('recorded_time', sa.DateTime(), nullable=False))
    op.alter_column('gps_tracking', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gps_tracking', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('gps_tracking', 'recorded_time')
    op.drop_column('gps_tracking', 'speed')
    op.drop_column('gps_tracking', 'longitude')
    op.drop_column('gps_tracking', 'latitude')
    # ### end Alembic commands ###
