"""update vehicle driver relationship

Revision ID: 2d95650efc8c
Revises: 0616a78a5b94
Create Date: 2026-08-13 19:59:30.113915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d95650efc8c'
down_revision: Union[str, Sequence[str], None] = '0616a78a5b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vehicles_driver_id'), 'vehicles', ['driver_id'], unique=False)
    op.drop_constraint(op.f('vehicles_driver_id_fkey'), 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'drivers', ['driver_id'], ['driver_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicles_driver_id_fkey'), 'vehicles', 'drivers', ['driver_id'], ['driver_id'])
    op.drop_index(op.f('ix_vehicles_driver_id'), table_name='vehicles')
    # ### end Alembic commands ###
