"""milestone2_gaps

Revision ID: 2f23de95710b
Revises: 00d6db80aadf
Create Date: 2026-08-15 16:22:54.224899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f23de95710b'
down_revision: Union[str, Sequence[str], None] = '00d6db80aadf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.add_column('shipments', sa.Column('expected_delivery', sa.String(length=255), nullable=True))
    op.add_column('trips', sa.Column('route_geometry', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'route_geometry')
    op.drop_column('shipments', 'expected_delivery')
    op.drop_table('shipment_events')
    # ### end Alembic commands ###
