"""add gps tracking fields

Revision ID: 346bec11a95b
Revises: 87ae1f6fe9dd
Create Date: 2026-08-10 18:26:48.895672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '346bec11a95b'
down_revision: Union[str, Sequence[str], None] = '87ae1f6fe9dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps_tracking', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('gps_tracking', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('gps_tracking', sa.Column('speed', sa.Float(), nullable=True))
    op.add_column('gps_tracking', sa.Column('recorded_time', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('gps_tracking', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gps_tracking', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('gps_tracking', 'recorded_time')
    op.drop_column('gps_tracking', 'speed')
    op.drop_column('gps_tracking', 'longitude')
    op.drop_column('gps_tracking', 'latitude')
    # ### end Alembic commands ###
