"""expand_milestone3_tables_final

Revision ID: 61401df232a7
Revises: 2d95650efc8c
Create Date: 2026-08-13 22:56:06.010155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61401df232a7'
down_revision: Union[str, Sequence[str], None] = '2d95650efc8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('attendance', sa.Column('check_in', sa.DateTime(), nullable=True))
    op.add_column('attendance', sa.Column('check_out', sa.DateTime(), nullable=True))
    op.add_column('attendance', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('attendance', sa.Column('remarks', sa.String(length=255), nullable=True))
    op.add_column('drivers', sa.Column('license_number', sa.String(length=50), nullable=True))
    op.add_column('drivers', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('drivers', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('drivers', sa.Column('status', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('drivers_user_id_fkey'), 'drivers', type_='foreignkey')
    op.create_foreign_key(None, 'drivers', 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
    op.add_column('fuel_records', sa.Column('driver_id', sa.UUID(), nullable=True))
    op.add_column('fuel_records', sa.Column('fuel_amount', sa.Float(), nullable=True))
    op.add_column('fuel_records', sa.Column('fuel_cost', sa.Float(), nullable=True))
    op.add_column('fuel_records', sa.Column('odometer_reading', sa.Float(), nullable=True))
    op.add_column('fuel_records', sa.Column('refill_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'fuel_records', 'drivers', ['driver_id'], ['driver_id'])
    op.add_column('notifications', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('notifications', sa.Column('alert_type', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('trips', 'start_location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('trips', 'destination',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('vehicle_maintenance', sa.Column('maintenance_type', sa.String(length=100), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('service_date', sa.DateTime(), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('next_service_date', sa.DateTime(), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('remarks', sa.String(length=500), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('performed_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_maintenance', 'performed_by')
    op.drop_column('vehicle_maintenance', 'status')
    op.drop_column('vehicle_maintenance', 'remarks')
    op.drop_column('vehicle_maintenance', 'cost')
    op.drop_column('vehicle_maintenance', 'next_service_date')
    op.drop_column('vehicle_maintenance', 'service_date')
    op.drop_column('vehicle_maintenance', 'maintenance_type')
    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('trips', 'destination',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('trips', 'start_location',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'alert_type')
    op.drop_column('notifications', 'title')
    op.drop_constraint(None, 'fuel_records', type_='foreignkey')
    op.drop_column('fuel_records', 'refill_date')
    op.drop_column('fuel_records', 'odometer_reading')
    op.drop_column('fuel_records', 'fuel_cost')
    op.drop_column('fuel_records', 'fuel_amount')
    op.drop_column('fuel_records', 'driver_id')
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.create_foreign_key(op.f('drivers_user_id_fkey'), 'drivers', 'users', ['user_id'], ['user_id'])
    op.drop_column('drivers', 'status')
    op.drop_column('drivers', 'address')
    op.drop_column('drivers', 'experience_years')
    op.drop_column('drivers', 'license_number')
    op.drop_column('attendance', 'remarks')
    op.drop_column('attendance', 'status')
    op.drop_column('attendance', 'check_out')
    op.drop_column('attendance', 'check_in')
    op.drop_column('attendance', 'date')
    # ### end Alembic commands ###
