"""initial schema

Revision ID: 689ff91092c4
Revises: 
Create Date: 2026-07-24 10:45:31.084562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '689ff91092c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'date')
    op.drop_column('attendance', 'status')
    op.drop_constraint(op.f('drivers_license_number_key'), 'drivers', type_='unique')
    op.create_unique_constraint(None, 'drivers', ['user_id'])
    op.drop_column('drivers', 'address')
    op.drop_column('drivers', 'status')
    op.drop_column('drivers', 'experience_years')
    op.drop_column('drivers', 'license_number')
    op.drop_column('drivers', 'created_at')
    op.drop_column('fuel_records', 'mileage')
    op.drop_column('fuel_records', 'fuel_amount')
    op.drop_column('fuel_records', 'refill_date')
    op.drop_column('fuel_records', 'fuel_cost')
    op.drop_column('gps_tracking', 'longitude')
    op.drop_column('gps_tracking', 'recorded_time')
    op.drop_column('gps_tracking', 'latitude')
    op.drop_column('gps_tracking', 'speed')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'message')
    op.drop_column('shipments', 'shipment_weight')
    op.drop_column('shipments', 'status')
    op.drop_column('shipments', 'tracking_number')
    op.drop_column('shipments', 'destination')
    op.drop_column('shipments', 'source')
    op.drop_column('shipments', 'created_at')
    op.drop_column('shipments', 'customer_name')
    op.drop_column('trips', 'distance')
    op.drop_column('trips', 'status')
    op.drop_column('trips', 'destination')
    op.drop_column('trips', 'start_time')
    op.drop_column('trips', 'end_time')
    op.drop_column('trips', 'start_location')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('vehicle_maintenance', 'next_service_date')
    op.drop_column('vehicle_maintenance', 'remarks')
    op.drop_column('vehicle_maintenance', 'status')
    op.drop_column('vehicle_maintenance', 'service_date')
    op.drop_column('vehicle_maintenance', 'maintenance_type')
    op.drop_column('vehicle_maintenance', 'cost')
    op.drop_constraint(op.f('vehicles_assigned_driver_fkey'), 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'assigned_driver')
    op.drop_column('vehicles', 'fuel_type')
    op.drop_column('vehicles', 'vehicle_type')
    op.drop_column('vehicles', 'status')
    op.drop_column('vehicles', 'brand')
    op.drop_column('vehicles', 'model')
    op.drop_column('vehicles', 'registration_number')
    op.drop_column('vehicles', 'manufacture_year')
    op.drop_column('vehicles', 'capacity')
    op.drop_column('vehicles', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('manufacture_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('registration_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('brand', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('vehicle_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('fuel_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('assigned_driver', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('vehicles_assigned_driver_fkey'), 'vehicles', 'drivers', ['assigned_driver'], ['driver_id'])
    op.add_column('vehicle_maintenance', sa.Column('cost', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('maintenance_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('service_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('next_service_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('trips', sa.Column('start_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('destination', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('distance', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('customer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('destination', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('tracking_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('shipment_weight', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('gps_tracking', sa.Column('speed', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('gps_tracking', sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('gps_tracking', sa.Column('recorded_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('gps_tracking', sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('fuel_records', sa.Column('fuel_cost', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('fuel_records', sa.Column('refill_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('fuel_records', sa.Column('fuel_amount', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('fuel_records', sa.Column('mileage', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('license_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'drivers', type_='unique')
    op.create_unique_constraint(op.f('drivers_license_number_key'), 'drivers', ['license_number'], postgresql_nulls_not_distinct=False)
    op.add_column('attendance', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
