"""add_route_type_to_trips

Revision ID: 76457837c2d0
Revises: 61401df232a7
Create Date: 2026-08-13 23:57:01.748954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76457837c2d0'
down_revision: Union[str, Sequence[str], None] = '61401df232a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('route_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'route_type')
    # ### end Alembic commands ###
