"""add vehicle fields

Revision ID: 9115d319a331
Revises: 689ff91092c4
Create Date: 2026-08-10 21:13:19.481958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9115d319a331'
down_revision: Union[str, Sequence[str], None] = '689ff91092c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('registration_number', sa.String(length=50), nullable=False))
    op.add_column('vehicles', sa.Column('vehicle_type', sa.String(length=50), nullable=False))
    op.add_column('vehicles', sa.Column('brand', sa.String(length=100), nullable=False))
    op.add_column('vehicles', sa.Column('model', sa.String(length=100), nullable=False))
    op.add_column('vehicles', sa.Column('manufacture_year', sa.Integer(), nullable=False))
    op.add_column('vehicles', sa.Column('fuel_type', sa.String(length=50), nullable=False))
    op.add_column('vehicles', sa.Column('capacity', sa.Float(), nullable=False))
    op.add_column('vehicles', sa.Column('driver_id', sa.UUID(), nullable=True))
    op.add_column('vehicles', sa.Column('status', sa.String(length=30), nullable=False))
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    op.create_foreign_key(None, 'vehicles', 'drivers', ['driver_id'], ['driver_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_column('vehicles', 'status')
    op.drop_column('vehicles', 'driver_id')
    op.drop_column('vehicles', 'capacity')
    op.drop_column('vehicles', 'fuel_type')
    op.drop_column('vehicles', 'manufacture_year')
    op.drop_column('vehicles', 'model')
    op.drop_column('vehicles', 'brand')
    op.drop_column('vehicles', 'vehicle_type')
    op.drop_column('vehicles', 'registration_number')
    # ### end Alembic commands ###
