"""finalize in-app notifications

Revision ID: b8c9d0e1f2a3
Revises: a7b8c9d0e1f2
Create Date: 2026-08-27
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "b8c9d0e1f2a3"
down_revision: Union[str, Sequence[str], None] = "a7b8c9d0e1f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Preserve the legacy maintenance delivery fields and all existing rows.
    op.add_column("notifications", sa.Column("title", sa.String(length=160), nullable=True))
    op.add_column("notifications", sa.Column("message", sa.Text(), nullable=True))
    op.add_column("notifications", sa.Column("type", sa.String(length=50), nullable=True))
    op.add_column(
        "notifications",
        sa.Column("is_read", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column("notifications", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
    op.alter_column("notifications", "alert_type", existing_type=sa.String(length=30), type_=sa.String(length=120))

    # Backfill old maintenance alert rows before making the in-app fields required.
    op.execute(
        """
        UPDATE notifications
        SET title = COALESCE(title, 'Maintenance Alert'),
            message = COALESCE(message, 'Maintenance notification generated by FleetFlow.'),
            type = COALESCE(type, 'maintenance'),
            created_at = COALESCE(created_at, sent_at, CURRENT_TIMESTAMP)
        """
    )
    op.alter_column("notifications", "title", nullable=False, server_default="FleetFlow notification")
    op.alter_column("notifications", "message", nullable=False, server_default="")
    op.alter_column("notifications", "type", nullable=False, server_default="system")
    op.alter_column("notifications", "created_at", nullable=False, server_default=sa.text("CURRENT_TIMESTAMP"))
    op.create_index("ix_notifications_created_at", "notifications", ["created_at"], unique=False)

    # The old key allowed one maintenance alert globally. Include user_id so
    # both Admin and FleetManager can receive the same maintenance event.
    op.drop_constraint("uq_notifications_maintenance_alert_type", "notifications", type_="unique")
    op.create_unique_constraint(
        "uq_notifications_maintenance_user_alert_type",
        "notifications",
        ["maintenance_id", "user_id", "alert_type"],
    )


def downgrade() -> None:
    op.drop_constraint("uq_notifications_maintenance_user_alert_type", "notifications", type_="unique")
    op.create_unique_constraint(
        "uq_notifications_maintenance_alert_type",
        "notifications",
        ["maintenance_id", "alert_type"],
    )
    op.drop_index("ix_notifications_created_at", table_name="notifications")
    op.alter_column("notifications", "alert_type", existing_type=sa.String(length=120), type_=sa.String(length=30))
    op.drop_column("notifications", "created_at")
    op.drop_column("notifications", "is_read")
    op.drop_column("notifications", "type")
    op.drop_column("notifications", "message")
    op.drop_column("notifications", "title")
