"""update vehicle table

Revision ID: e997350ce276
Revises: 0f06bf179388
Create Date: 2026-08-06 21:54:16.330292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e997350ce276'
down_revision: Union[str, Sequence[str], None] = '0f06bf179388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    vehicle_status = postgresql.ENUM(
    'Available',
    'Assigned',
    'Maintenance',
    'In Transit',
    name='vehicle_status'
    )

    vehicle_status.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('registration_number', sa.String(length=20), nullable=False))
    op.add_column('vehicles', sa.Column('vehicle_type', sa.String(length=50), nullable=False))
    op.add_column('vehicles', sa.Column('brand', sa.String(length=50), nullable=False))
    op.add_column('vehicles', sa.Column('model', sa.String(length=50), nullable=False))
    op.add_column('vehicles', sa.Column('manufacture_year', sa.Integer(), nullable=False))
    op.add_column('vehicles', sa.Column('fuel_type', sa.String(length=30), nullable=False))
    op.add_column('vehicles', sa.Column('capacity', sa.Integer(), nullable=False))
    op.add_column('vehicles', sa.Column('assigned_driver', sa.UUID(), nullable=True))
    op.add_column(
        'vehicles',
        sa.Column(
            'status',
            sa.Enum('Available', 'Assigned', 'Maintenance', 'In Transit', name='vehicle_status'),
            nullable=False,
            server_default='Available',
        ),
    )
    op.add_column('vehicles', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('vehicles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(None, 'vehicles', ['registration_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_column('vehicles', 'updated_at')
    op.drop_column('vehicles', 'created_at')
    op.drop_column('vehicles', 'status')
    op.drop_column('vehicles', 'assigned_driver')
    op.drop_column('vehicles', 'capacity')
    op.drop_column('vehicles', 'fuel_type')
    op.drop_column('vehicles', 'manufacture_year')
    op.drop_column('vehicles', 'model')
    op.drop_column('vehicles', 'brand')
    op.drop_column('vehicles', 'vehicle_type')
    op.drop_column('vehicles', 'registration_number')
    vehicle_status = postgresql.ENUM(
    'Available',
    'Assigned',
    'Maintenance',
    'In Transit',
    name='vehicle_status'
    )

    vehicle_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
