"""estimated_duration

Revision ID: fbeecfc81372
Revises: 2f23de95710b
Create Date: 2026-08-15 17:05:01.768692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbeecfc81372'
down_revision: Union[str, Sequence[str], None] = '2f23de95710b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('estimated_duration', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'estimated_duration')
    # ### end Alembic commands ###
