import { useCallback, useContext, useEffect, useState } from "react";
import { Navigate } from "react-router-dom";
import MainLayout from "../layouts/MainLayout";
import EmptyState from "../components/EmptyState";
import LoadingCard from "../components/LoadingCard";
import PageHeader from "../components/PageHeader";
import SearchBar from "../components/SearchBar";
import api from "../services/api";
import { AuthContext } from "../context/auth-context";
import "./FuelLog.css";

const emptyForm = { vehicle_id: "", fuel_amount: "", fuel_cost: "", mileage: "", refill_date: "" };
const toInputDateTime = (value) => value ? new Date(value).toISOString().slice(0, 16) : "";
const money = (value) => `₹${Number(value || 0).toLocaleString(undefined, { maximumFractionDigits: 2 })}`;

function FuelLog() {
  const { user } = useContext(AuthContext);
  const [records, setRecords] = useState([]); const [vehicles, setVehicles] = useState([]); const [query, setQuery] = useState(""); const [vehicleFilter, setVehicleFilter] = useState("All"); const [fromDate, setFromDate] = useState(""); const [toDate, setToDate] = useState(""); const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState(null); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const canManage = ["Admin", "FleetManager"].includes(user?.role); const isDriver = user?.role === "Driver"; const isDispatcher = user?.role === "Dispatcher"; const canRead = canManage || isDispatcher || isDriver; const canUseVehicleFilters = !isDriver;
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [recordResponse, vehicleResponse] = await Promise.all([api.get("/fuel-records/"), canUseVehicleFilters ? api.get("/vehicles/") : Promise.resolve({ data: [] })]); setRecords(recordResponse.data); setVehicles(vehicleResponse.data); } catch (requestError) { setError(requestError.response?.data?.detail || "Unable to load fuel records."); } finally { setLoading(false); } }, [canUseVehicleFilters]);
  useEffect(() => { if (!canRead) return undefined; const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [canRead, load]);
  if (!canRead && user) return <Navigate to="/dashboard" replace />;
  const vehicleName = (vehicleId) => vehicles.find((vehicle) => vehicle.vehicle_id === vehicleId)?.registration_number || vehicleId?.slice(0, 8) || "Unknown vehicle";
  const filteredRecords = records.filter((record) => { const date = record.refill_date ? new Date(record.refill_date) : null; const matchesQuery = !query.trim() || vehicleName(record.vehicle_id).toLowerCase().includes(query.trim().toLowerCase()) || String(record.fuel_reference || "").toLowerCase().includes(query.trim().toLowerCase()); const matchesVehicle = vehicleFilter === "All" || record.vehicle_id === vehicleFilter; const matchesFrom = !fromDate || (date && date >= new Date(`${fromDate}T00:00:00`)); const matchesTo = !toDate || (date && date <= new Date(`${toDate}T23:59:59`)); return matchesQuery && matchesVehicle && matchesFrom && matchesTo; });
  const showCreate = () => { setEditing(null); setForm({ ...emptyForm, refill_date: toInputDateTime(new Date()) }); setError(""); setOpen(true); };
  const showEdit = (record) => { setEditing(record); setForm({ vehicle_id: record.vehicle_id || "", fuel_amount: record.fuel_amount ?? "", fuel_cost: record.fuel_cost ?? "", mileage: record.mileage ?? "", refill_date: toInputDateTime(record.refill_date) }); setError(""); setOpen(true); };
  const closeForm = () => { if (!saving) { setOpen(false); setEditing(null); setForm(emptyForm); } };
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const payload = { vehicle_id: form.vehicle_id, fuel_amount: Number(form.fuel_amount), fuel_cost: Number(form.fuel_cost), mileage: Number(form.mileage), refill_date: new Date(form.refill_date).toISOString() }; const response = editing ? await api.put(`/fuel-records/${editing.fuel_id}`, payload) : await api.post("/fuel-records/", payload); setNotice(editing ? `Fuel record ${response.data.fuel_reference || editing.fuel_id} updated successfully.` : `Fuel record created successfully: ${response.data.fuel_reference || response.data.fuel_id}`); closeForm(); await load(); } catch (requestError) { setError(requestError.response?.data?.detail || "Unable to save fuel record."); } finally { setSaving(false); } };
  const remove = async (record) => { if (!window.confirm(`Delete fuel record ${record.fuel_reference || record.fuel_id}? This cannot be undone.`)) return; setSaving(true); setError(""); try { await api.delete(`/fuel-records/${record.fuel_id}`); setNotice(`Fuel record ${record.fuel_reference || record.fuel_id} deleted.`); await load(); } catch (requestError) { setError(requestError.response?.data?.detail || "Unable to delete fuel record."); } finally { setSaving(false); } };
  if (loading) return <MainLayout><LoadingCard message="Loading fuel records..." /></MainLayout>;
  return <MainLayout><PageHeader eyebrow="Fuel Monitoring" title={isDriver ? "My Fuel Records" : isDispatcher ? "Fuel Log (Read Only)" : "Fuel Log"} description={isDriver ? "Read-only fuel records for your currently assigned vehicle." : isDispatcher ? "Read-only fuel records across the fleet." : "Record refills, monitor fuel cost, and maintain accurate vehicle mileage."} actionLabel={canManage ? "Add Fuel Record" : undefined} actionTo={undefined} />
    <div className="fuel-page-actions">{canManage && <button className="primary-button" onClick={showCreate}>Add Fuel Record</button>}<button className="fuel-refresh" onClick={() => void load()} disabled={saving}>Refresh</button></div>
    {notice && <div className="fuel-notice" role="status">{notice}<button onClick={() => setNotice("")} aria-label="Dismiss success message">×</button></div>}{error && !open && <div className="fuel-error">{error}</div>}
    <section className="fuel-toolbar"><SearchBar value={query} onChange={(event) => setQuery(event.target.value)} placeholder={isDriver ? "Search my fuel records" : "Search vehicle or Fuel ID"} />{canUseVehicleFilters && <select value={vehicleFilter} onChange={(event) => setVehicleFilter(event.target.value)} aria-label="Filter fuel records by vehicle"><option value="All">All vehicles</option>{vehicles.map((vehicle) => <option key={vehicle.vehicle_id} value={vehicle.vehicle_id}>{vehicle.registration_number}</option>)}</select>}<label>From<input type="date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} /></label><label>To<input type="date" value={toDate} onChange={(event) => setToDate(event.target.value)} /></label></section>
    {!filteredRecords.length ? <EmptyState title={records.length ? "No matching fuel records" : isDriver ? "No fuel records for your assigned vehicle" : "No fuel records yet"} description={records.length ? "Try another date range or search term." : isDriver ? "Fuel records will appear here when your assigned vehicle has a recorded refill." : "Fuel refills will appear here after an Admin or Fleet Manager records one."} action={canManage ? <button className="primary-button" onClick={showCreate}>Add Fuel Record</button> : null} /> : <section className="fuel-table-card"><div className="fuel-table-wrap"><table><thead><tr><th>Fuel ID</th><th>Vehicle</th><th>Fuel amount</th><th>Fuel cost</th><th>Mileage</th><th>Refill date</th>{canManage && <th>Actions</th>}</tr></thead><tbody>{filteredRecords.map((record) => <tr key={record.fuel_id}><td><strong>{record.fuel_reference || record.fuel_id}</strong></td><td>{vehicleName(record.vehicle_id)}</td><td>{record.fuel_amount == null ? "—" : `${record.fuel_amount} L`}</td><td>{record.fuel_cost == null ? "—" : money(record.fuel_cost)}</td><td>{record.mileage == null ? "—" : `${Number(record.mileage).toLocaleString()} km`}</td><td>{record.refill_date ? new Date(record.refill_date).toLocaleString() : "—"}</td>{canManage && <td className="fuel-row-actions"><button onClick={() => showEdit(record)} disabled={saving}>Edit</button><button className="danger" onClick={() => void remove(record)} disabled={saving}>Delete</button></td>}</tr>)}</tbody></table></div></section>}
    {open && <div className="fuel-modal-backdrop" role="presentation"><section className="fuel-modal" role="dialog" aria-modal="true" aria-labelledby="fuel-form-title"><div className="fuel-modal-header"><div><p>{editing ? "Edit fuel record" : "New fuel record"}</p><h2 id="fuel-form-title">{editing ? "Update fuel log" : "Add fuel log"}</h2>{editing && <span>Fuel ID: <strong>{editing.fuel_reference || editing.fuel_id}</strong></span>}</div><button onClick={closeForm} disabled={saving} aria-label="Close fuel form">×</button></div>{error && <div className="fuel-error">{error}</div>}<form onSubmit={submit}><div className="fuel-form-grid"><label>Vehicle<span>*</span><select required value={form.vehicle_id} onChange={(event) => setForm({ ...form, vehicle_id: event.target.value })}><option value="">Select vehicle</option>{vehicles.map((vehicle) => <option key={vehicle.vehicle_id} value={vehicle.vehicle_id}>{vehicle.registration_number} — {vehicle.status}</option>)}</select></label><label>Fuel Amount (L)<span>*</span><input required min="0.001" step="0.001" type="number" value={form.fuel_amount} onChange={(event) => setForm({ ...form, fuel_amount: event.target.value })} /></label><label>Fuel Cost (₹)<span>*</span><input required min="0" step="0.01" type="number" value={form.fuel_cost} onChange={(event) => setForm({ ...form, fuel_cost: event.target.value })} /></label><label>Mileage (km)<span>*</span><input required min="0" step="0.01" type="number" value={form.mileage} onChange={(event) => setForm({ ...form, mileage: event.target.value })} /></label><label className="fuel-full">Refill Date<span>*</span><input required type="datetime-local" value={form.refill_date} onChange={(event) => setForm({ ...form, refill_date: event.target.value })} /></label></div><div className="fuel-form-actions"><button type="button" onClick={closeForm} disabled={saving}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? "Saving..." : editing ? "Save Changes" : "Create Fuel Record"}</button></div></form></section></div>}
  </MainLayout>;
}
export default FuelLog;
